# Generated by Django 3.2 on 2021-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerproduct',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pizzaproduct',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
