# Generated by Django 3.2 on 2021-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210519_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pizzaproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
