# Generated by Django 3.2 on 2021-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210521_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
