# Generated by Django 3.2 on 2021-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_cart_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
